<? 
include 'includes.php';
$title = 'Publications';
$curr = 'pubs';
phead($title);
ptabs($curr);
?>

<div style="padding-top: 30px;">
<h2> Publications </h2>
<ol>
  <li class='pub' >Hughes M, Deharo L, Pulivarthy SR, Gu J, Hayes K, Panda S, <b>Hogenesch JB</b>: <i>High-resolution Time Course Analysis of Gene Expression from Pituitary</i>. <b><i>Cold Spring Harbor symposia on quantitative biology</i></b><i> </i>2007, 72:381-386.</li>
  <li class='pub' >Amelio AL, Miraglia LJ, Conkright JJ, Mercer BA, Batalov S, Cavett V, Orth AP, Busby J, <b>Hogenesch JB*</b>, Conkright MD*: <i>A coactivator trap identifies NONO (p54nrb) as a component of the cAMP-signaling pathway</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2007, 104(51):20314-20319.<span class="s1"> </span>*Co-corresponding author</li>
  <li class='pub' >Kozlov SV, Bogenpohl JW, Howell MP, Wevrick R, Panda S, <b>Hogenesch JB</b>, Muglia LJ, Van Gelder RN, Herzog ED, Stewart CL: <i>The imprinted gene Magel2 regulates normal circadian output</i>. <b><i>Nature genetics</i></b><i> </i>2007, 39(10):1266-1272.</li>
  <li class='pub' >Halsey TA, Yang L, Walker JR, <b>Hogenesch JB</b>, Thomas RS: <i>A functional map of NFkappaB signaling identifies novel modulators and multiple system controls</i>. <b><i>Genome Biol</i></b><i> </i>2007, 8(6):R104.</li>
  <li class='pub' >McCarthy JJ, Andrews JL, McDearmon EL, Campbell KS, Barber BK, Miller BH, Walker JR, <b>Hogenesch JB</b>, Takahashi JS, Esser KA: <i>Identification of the Circadian Transcriptome in Adult Mouse Skeletal Muscle</i>. <b><i>Physiol Genomics</i></b><i> </i>2007.</li>
  <li class='pub' >Su AI, <b>Hogenesch JB</b>: <i>Power-law-like distributions in biomedical publications and research funding</i>. <b><i>Genome Biol</i></b><i> </i>2007, 8(4):404.</li>
  <li class='pub' >Miller BH, McDearmon EL, Panda S, Hayes KR, Zhang J, Andrews JL, Antoch MP, Walker JR, Esser KA, <b>Hogenesch JB</b>, Takahashi JS: <i>Circadian and CLOCK-controlled regulation of the mouse transcriptome and cell proliferation</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2007, 104(9):3342-3347.</li>
  <li class='pub' >Lee K, Burgoon LD, Lamb L, Dere E, Zacharewski TR, <b>Hogenesch JB</b>, LaPres JJ: <i>Identification and characterization of genes susceptible to transcriptional cross-talk between the hypoxia and dioxin signaling cascades</i>. <b><i>Chemical research in toxicology</i></b><i> </i>2006, 19(10):1284-1293.</li>
  <li class='pub' >Sato TK, Yamada RG, Ukai H, Baggs JE, Miraglia LJ, Kobayashi TJ, Welsh DK, Kay SA, Ueda HR, <b>Hogenesch JB</b>: <i>Feedback repression is required for mammalian circadian clock function</i>. <b><i>Nature genetics</i></b><i> </i>2006, 38(3):312-319.</li>
  <li class='pub' >Gurkan C, Lapp H, Alory C, Su AI, <b>Hogenesch JB</b>, Balch WE: <i>Large-scale profiling of Rab GTPase trafficking networks: the membrome</i>. <b><i>Molecular biology of the cell</i></b><i> </i>2005, 16(8):3847-3864.</li>
  <li class='pub' >Rudic RD, McNamara P, Reilly D, Grosser T, Curtis AM, Price TS, Panda S, <b>Hogenesch JB</b>, FitzGerald GA: <i>Bioinformatic analysis of circadian gene oscillation in mouse aorta</i>. <b><i>Circulation</i></b><i> </i>2005, 112(17):2716-2724.</li>
  <li class='pub' >Baggs JE, Hayes KR, <b>Hogenesch JB</b>: <i>Comparative genomics as a tool in the understanding of eukaryotic transcriptional regulation</i>. <b><i>Current opinion in genetics &amp; development</i></b><i> </i>2005, 15(6):634-639.</li>
  <li class='pub' >Willingham AT, Orth AP, Batalov S, Peters EC, Wen BG, Aza-Blanc P, <b>Hogenesch JB*</b>, Schultz PG*: <i>A strategy for probing the function of noncoding RNAs finds a repressor of NFAT</i>. <b><i>Science (New York, NY</i></b><i> </i>2005, 309(5740):1570-1573.<a href="#foot1"> <sup>[1]</sup></a><span class="s1"> </span>*Co-corresponding author</li>
  <li class='pub' >Harada JN, Bower KE, Orth AP, Callaway S, Nelson CG, Laris C, <b>Hogenesch JB</b>, Vogt PK, Chanda SK: <i>Identification of novel mammalian growth regulatory factors by genome-scale quantitative image analysis</i>. <b><i>Genome research</i></b><i> </i>2005, 15(8):1136-1144.</li>
  <li class='pub' >Gurkan C, Lapp H, <b>Hogenesch JB</b>, Balch WE: <i>Exploring trafficking GTPase function by mRNA expression profiling: use of the SymAtlas web-application and the Membrome datasets</i>. <b><i>Methods in enzymology</i></b><i> </i>2005, 403:1-10.</li>
  <li class='pub' >Vengellur A, Phillips JM, <b>Hogenesch JB</b>, LaPres JJ: <i>Gene expression profiling of hypoxia signaling in human hepatocellular carcinoma cells</i>. <b><i>Physiol Genomics</i></b><i> </i>2005, 22(3):308-318.</li>
  <li class='pub' >Hayes KR, Baggs JE, <b>Hogenesch JB</b>: <i>Circadian clocks are seeing the systems biology light</i>. <b><i>Genome Biol</i></b><i> </i>2005, 6(5):219.</li>
  <li class='pub' >Walker JR, <b>Hogenesch JB</b>: <i>RNA profiling in circadian biology</i>. <b><i>Methods in enzymology</i></b><i> </i>2005, 393:366-376.</li>
  <li class='pub' >Zhang X, Odom DT, Koo SH, Conkright MD, Canettieri G, Best J, Chen H, Jenner R, Herbolsheimer E, Jacobsen E, Kadam S, Ecker JR, Emerson B, <b>Hogenesch JB</b>, Unterman T, Young RA, Montminy M: <i>Genome-wide analysis of cAMP-response element binding protein occupancy, phosphorylation, and target gene activation in human tissues</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2005, 102(12):4459-4464.</li>
  <li class='pub' >Sandberg ML, Sutton SE, Pletcher MT, Wiltshire T, Tarantino LM, <b>Hogenesch JB</b>, Cooke MP: <i>c-Myb and p300 regulate hematopoietic stem cell proliferation and differentiation</i>. <b><i>Developmental cell</i></b><i> </i>2005, 8(2):153-166.</li>
  <li class='pub' >Panda S, Nayak SK, Campo B, Walker JR, <b>Hogenesch JB</b>, Jegla T: <i>Illumination of the melanopsin signaling pathway</i>. <b><i>Science (New York, NY</i></b><i> </i>2005, 307(5709):600-604.<a href="#foot2"> <sup>[2]</sup></a></li>
  <li class='pub' >Panda S, <b>Hogenesch JB</b>: <i>It's all in the timing: many clocks, many outputs</i>. <b><i>Journal of biological rhythms</i></b><i> </i>2004, 19(5):374-387.</li>
  <li class='pub' >Rudic RD, McNamara P, Curtis AM, Boston RC, Panda S, <b>Hogenesch JB</b>, Fitzgerald GA: <i>BMAL1 and CLOCK, two essential components of the circadian clock, are involved in glucose homeostasis</i>. <b><i>PLoS biology</i></b><i> </i>2004, 2(11):e377.<a href="#foot3"> <sup>[3]</sup></a></li>
  <li class='pub' >Joseph SB, Bradley MN, Castrillo A, Bruhn KW, Mak PA, Pei L, <b>Hogenesch JB</b>, O'Connell R M, Cheng G, Saez E, Miller JF, Tontonoz P: <i>LXR-dependent gene expression is important for macrophage survival and the innate immune response</i>. <b><i>Cell</i></b><i> </i>2004, 119(2):299-309.</li>
  <li class='pub' >Sato TK, Panda S, Miraglia LJ, Reyes TM, Rudic RD, McNamara P, Naik KA, FitzGerald GA, Kay SA, <b>Hogenesch JB</b>: <i>A functional genomics strategy reveals Rora as a component of the mammalian circadian clock</i>. <b><i>Neuron</i></b><i> </i>2004, 43(4):527-537.<a href="#foot4"> <sup>[4]</sup></a></li>
  <li class='pub' >Su AI, Wiltshire T, Batalov S, Lapp H, Ching KA, Block D, Zhang J, Soden R, Hayakawa M, Kreiman G, Cooke MP, Walker JR, <b>Hogenesch JB</b>: <i>A gene atlas of the mouse and human protein-encoding transcriptomes</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2004, 101(16):6062-6067.</li>
  <li class='pub' >Walker JR, Su AI, Self DW, <b>Hogenesch JB</b>, Lapp H, Maier R, Hoyer D, Bilbe G: <i>Applications of a rat multiple tissue gene expression data set</i>. <b><i>Genome research</i></b><i> </i>2004, 14(4):742-749.</li>
  <li class='pub' >Ueda HR, Hayashi S, Matsuyama S, Yomo T, Hashimoto S, Kay SA, <b>Hogenesch JB</b>, Iino M: <i>Universality and flexibility in gene expression from bacteria to human</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2004, 101(11):3765-3769.</li>
  <li class='pub' >Van Gelder RN, <b>Hogenesch JB</b>: <i>Clean thoughts about dirty genes</i>. <b><i>Journal of biological rhythms</i></b><i> </i>2004, 19(1):3-9.</li>
  <li class='pub' ><b>Hogenesch JB</b>, Panda S, Kay S, Takahashi JS: <i>Circadian transcriptional output in the SCN and liver of the mouse</i>. <b><i>Novartis Foundation symposium</i></b><i> </i>2003, 253:171-180; discussion 152-175, 102-179, 180-173 passim.</li>
  <li class='pub' >Panda S, Sato TK, Hampton GM, <b>Hogenesch JB</b>: <i>An array of insights: application of DNA chip technology in the study of cell biology</i>. <b><i>Trends in cell biology</i></b><i> </i>2003, 13(3):151-156.</li>
  <li class='pub' >Grechez-Cassiau A, Panda S, Lacoche S, Teboul M, Azmi S, Laudet V, <b>Hogenesch JB</b>, Taneja R, Delaunay F: <i>The transcriptional repressor STRA13 regulates a subset of peripheral circadian outputs</i>. <b><i>The Journal of biological chemistry</i></b><i> </i>2004, 279(2):1141-1150.</li>
  <li class='pub' >Conkright MD, Guzman E, Flechner L, Su AI, <b>Hogenesch JB*</b>, Montminy M*: <i>Genome-wide analysis of CREB target genes reveals a core promoter requirement for cAMP responsiveness</i>. <b><i>Molecular cell</i></b><i> </i>2003, 11(4):1101-1108.<span class="s1"> </span>*Co-corresponding author</li>
  <li class='pub' >Chanda SK, White S, Orth AP, Reisdorph R, Miraglia L, Thomas RS, DeJesus P, Mason DE, Huang Q, Vega R, Yu DH, Nelson CG, Smith BM, Terry R, Linford AS, Yu Y, Chirn GW, Song C, Labow MA, Cohen D, King FJ, Peters EC, Schultz PG, Vogt PK, <b>Hogenesch JB</b>, Caldwell JS: <i>Genome-scale functional profiling of the mammalian AP-1 signaling pathway</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2003, 100(21):12153-12158.</li>
  <li class='pub' >Reyes TM, Walker JR, DeCino C, <b>Hogenesch JB</b>, Sawchenko PE: <i>Categorically distinct acute stressors elicit dissimilar transcriptional profiles in the paraventricular nucleus of the hypothalamus</i>. <b><i>J Neurosci</i></b><i> </i>2003, 23(13):5607-5616.</li>
  <li class='pub' >Panda S, Provencio I, Tu DC, Pires SS, Rollag MD, Castrucci AM, Pletcher MT, Sato TK, Wiltshire T, Andahazy M, Kay SA, Van Gelder RN, <b>Hogenesch JB</b>: <i>Melanopsin is required for non-image-forming photic responses in blind mice</i>. <b><i>Science (New York, NY</i></b><i> </i>2003, 301(5632):525-527.</li>
  <li class='pub' >Conkright MD, Canettieri G, Screaton R, Guzman E, Miraglia L, <b>Hogenesch JB</b>, Montminy M: <i>TORCs: transducers of regulated CREB activity</i>. <b><i>Molecular cell</i></b><i> </i>2003, 12(2):413-423.</li>
  <li class='pub' >Downes M, Verdecia MA, Roecker AJ, Hughes R, <b>Hogenesch JB</b>, Kast-Woelbern HR, Bowman ME, Ferrer JL, Anisfeld AM, Edwards PA, Rosenfeld JM, Alvarez JG, Noel JP, Nicolaou KC, Evans RM: <i>A chemical, genetic, and structural analysis of the nuclear bile acid receptor FXR</i>. <b><i>Molecular cell</i></b><i> </i>2003, 11(4):1079-1092.<a href="#foot5"> <sup>[5]</sup></a></li>
  <li class='pub' >Sato TK, Panda S, Kay SA, <b>Hogenesch JB</b>: <i>DNA arrays: applications and implications for circadian biology</i>. <b><i>Journal of biological rhythms</i></b><i> </i>2003, 18(2):96-105.</li>
  <li class='pub' >Panda S, <b>Hogenesch JB</b>, Kay SA: <i>Circadian light input in plants, flies and mammals</i>. <b><i>Novartis Foundation symposium</i></b><i> </i>2003, 253:73-82; discussion 82-78, 102-109, 281-104.</li>
  <li class='pub' >Ceriani MF, <b>Hogenesch JB</b>, Yanovsky M, Panda S, Straume M, Kay SA: <i>Genome-wide expression analysis in Drosophila reveals genes controlling circadian behavior</i>. <b><i>J Neurosci</i></b><i> </i>2002, 22(21):9305-9319.</li>
  <li class='pub' >Li S, Liao J, Cutler G, Hoey T, <b>Hogenesch JB</b>, Cooke MP, Schultz PG, Ling XB: <i>Comparative analysis of human genome assemblies reveals genome-level differences</i>. <b><i>Genomics</i></b><i> </i>2002, 80(2):138-139.</li>
  <li class='pub' >Peier AM, Reeve AJ, Andersson DA, Moqrich A, Earley TJ, Hergarden AC, Story GM, Colley S, <b>Hogenesch JB</b>, McIntyre P, Bevan S, Patapoutian A: <i>A heat-sensitive TRP channel expressed in keratinocytes</i>. <b><i>Science (New York, NY</i></b><i> </i>2002, 296(5575):2046-2049.<a href="#foot6"> <sup>[6]</sup></a></li>
  <li class='pub' >Panda S, Sato TK, Castrucci AM, Rollag MD, DeGrip WJ, <b>Hogenesch JB</b>, Provencio I, Kay SA: <i>Melanopsin (Opn4) requirement for normal light-induced circadian phase shifting</i>. <b><i>Science (New York, NY</i></b><i> </i>2002, 298(5601):2213-2216.<a href="#foot7"> <sup>[7]</sup></a></li>
  <li class='pub' >Panda S, <b>Hogenesch JB</b>, Kay SA: <i>Circadian rhythms from flies to human</i>. <b><i>Nature</i></b><i> </i>2002, 417(6886):329-335.</li>
  <li class='pub' >Su AI, Cooke MP, Ching KA, Hakak Y, Walker JR, Wiltshire T, Orth AP, Vega RG, Sapinoso LM, Moqrich A, Patapoutian A, Hampton GM, Schultz PG, <b>Hogenesch JB</b>: <i>Large-scale analysis of the human and mouse transcriptomes</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2002, 99(7):4465-4470.</li>
  <li class='pub' >Panda S, Antoch MP, Miller BH, Su AI, Schook AB, Straume M, Schultz PG, Kay SA, Takahashi JS, <b>Hogenesch JB</b>: <i>Coordinated transcription of key pathways in the mouse by the circadian clock</i>. <b><i>Cell</i></b><i> </i>2002, 109(3):307-320.</li>
  <li class='pub' ><b>Hogenesch JB</b>, Ching KA, Batalov S, Su AI, Walker JR, Zhou Y, Kay SA, Schultz PG, Cooke MP: <i>A comparison of the Celera and Ensembl predicted gene sets reveals little overlap in novel genes</i>. <b><i>Cell</i></b><i> </i>2001, 106(4):413-415.<a href="#foot8"> <sup>[8]</sup></a></li>
  <li class='pub' >Reyes TM, Lewis K, Perrin MH, Kunitake KS, Vaughan J, Arias CA, <b>Hogenesch JB</b>, Gulyas J, Rivier J, Vale WW, Sawchenko PE: <i>Urocortin II: a member of the corticotropin-releasing factor (CRF) neuropeptide family that is selectively bound by type 2 CRF receptors</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>2001, 98(5):2843-2848.</li>
  <li class='pub' >Bunger MK, Wilsbacher LD, Moran SM, Clendenin C, Radcliffe LA, <b>Hogenesch JB</b>, Simon MC, Takahashi JS, Bradfield CA: <i>Mop3 is an essential component of the master circadian pacemaker in mammals</i>. <b><i>Cell</i></b><i> </i>2000, 103(7):1009-1017.</li>
  <li class='pub' >Harmer SL, <b>Hogenesch JB</b>, Straume M, Chang HS, Han B, Zhu T, Wang X, Kreps JA, Kay SA: <i>Orchestrated transcription of key pathways in Arabidopsis by the circadian clock</i>. <b><i>Science (New York, NY</i></b><i> </i>2000, 290(5499):2110-2113.</li>
  <li class='pub' ><b>Hogenesch JB</b>, Gu YZ, Moran SM, Shimomura K, Radcliffe LA, Takahashi JS, Bradfield CA: <i>The basic helix-loop-helix-PAS protein MOP9 is a brain-specific heterodimeric partner of circadian and hypoxia factors</i>. <b><i>J Neurosci</i></b><i> </i>2000, 20(13):RC83.</li>
  <li class='pub' >Gu YZ, <b>Hogenesch JB</b>, Bradfield CA: <i>The PAS superfamily: sensors of environmental and developmental signals</i>. <b><i>Annual review of pharmacology and toxicology</i></b><i> </i>2000, 40:519-561.</li>
  <li class='pub' >Gu YZ, Moran SM, <b>Hogenesch JB</b>, Wartman L, Bradfield CA: <i>Molecular characterization and chromosomal localization of a third alpha-class hypoxia inducible factor subunit, HIF3alpha</i>. <b><i>Gene expression</i></b><i> </i>1998, 7(3):205-213.</li>
  <li class='pub' ><b>Hogenesch JB</b>, Gu YZ, Jain S, Bradfield CA: <i>The basic-helix-loop-helix-PAS orphan MOP3 forms transcriptionally active complexes with circadian and hypoxia factors</i>. <b><i>Proceedings of the National Academy of Sciences of the United States of America</i></b><i> </i>1998, 95(10):5474-5479.<a href="#foot9"> <sup>[9]</sup></a></li>
  <li class='pub' ><b>Hogenesch JB</b>, Chan WK, Jackiw VH, Brown RC, Gu YZ, Pray-Grant M, Perdew GH, Bradfield CA: <i>Characterization of a subset of the basic-helix-loop-helix-PAS superfamily that interacts with components of the dioxin signaling pathway</i>. <b><i>The Journal of biological chemistry</i></b><i> </i>1997, 272(13):8581-8593.</li>
  <li class='pub' >Luo G, Gu YZ, Jain S, Chan WK, Carr KM, <b>Hogenesch JB</b>, Bradfield CA: <i>Molecular characterization of the murine Hif-1 alpha locus</i>. <b><i>Gene expression</i></b><i> </i>1997, 6(5):287-299.</li>
  <li class='pub' >Carver LA, <b>Hogenesch JB</b>, Bradfield CA: <i>Tissue specific expression of the rat Ah-receptor and ARNT mRNAs</i>. <b><i>Nucleic acids research</i></b><i> </i>1994, 22(15):3038-3044.</li>
</ol>
<hr/>
<ol>
  <li class='comment_pub' ><a id="foot1"/>Comment in Science. 2005 Sep 2;309(5740):1527-8.</li>
  <li class='comment_pub' ><a id="foot2"/>Comment in Nature. 2005 Feb 17;433(7027):698-9.</li>
  <li class='comment_pub' ><a id="foot3"/>Comment in Nature Med. 2006 Jan 12(1):54-55</li>
  <li class='comment_pub' ><a id="foot4"/>Comment in Neuron. 2004 Aug 19;43(4):443-6.</li>
  <li class='comment_pub' ><a id="foot5"/>Comment in Mol Cell. 2003 Apr;11(4):850-1.</li>
  <li class='comment_pub' ><a id="foot6"/>Comment in Current Biology. 2003 Jun 13 (12):476-478, Science Top 10 Breakthroughs of the Year 2002</li>
  <li class='comment_pub' ><a id="foot7"/>Comment in Science. 2003 Jan 10;299(5604):213-4, Science Top 10 Breakthroughs of the Year 2002</li>
  <li class='comment_pub' ><a id="foot8"/>Comment in Cell. 2002 May 3;109(3):283-4 and The Scientist 15 2001 Oct (20): 1</li>
  <li class='comment_pub' ><a id="foot9"/>Comment in Science. 1998 Jun 5;280(5369):1548-9 and Trends Cell Biol. 1998 Sep;8(9):342-3.</li>
</ul>

</div>
<? pfoot(); ?>
